package:
  name: kraken
  version: {{ environ['VERSION'] }}

source:
  path: ..

requirements:
  build:
     - python>=3.7
     - setuptools
     - pbr
  run:
     - python>=3.7
     - python-bidi
     - lxml
     - future
     - regex
     - requests
     - click>=7.0
     - numpy=1.19.5
     - pillow>=6.2.2
     - scipy
     - protobuf>=3.0
     - jinja2
     - torchvision-cpu=0.9.0
     - cpuonly
     - pytorch=1.8.0
     - jsonschema
     - scikit-image<=0.17.2
     - shapely
     - pip
     - imagemagick
     - coremltools>=3.3
     - pyvips

about:
  home: http://kraken.re
  license: Apache License
  summary: 'OCR/HTR engine for all the languages'
